# Generated by Django 3.2.24 on 2024-02-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_miuntes',
            new_name='time_minutes',
        ),
    ]
