from django.urls import include
from django.urls import path
from recipe import views
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register('recipes', views.RecipeViewSet) ### autogenerated urls

app_name = 'recipe'

urlpatterns = [
    path('', include(router.urls))
]